#To guess square root of randomly generated number
g = int (input("Give a preliminary guess: "))
import random
import math

x= int(random.random()*20)
print ("random number generated is",x)
flag = 0; 
y=math.sqrt(x)
print ("square root of random number is",y)
squareNumber= 0
def Iteration(int):
    global g
    print("function call")    
    
    while x!=0:
        if (x==(g*g)):
          return g  
          break
        else:
          g= ((g+(x/g))/2)
          continue
      
      
Iteration (g)
print ("The number generated by system is",g)